name: 'Secret Exists'
description: 'GitHub Action returning either true or false based on existence of a given secret'
inputs:
  secret-name:  # id of input
    description: 'name of secret to check existence of'
    required: true
outputs:
  exists: # output will be available to future steps
    description: 'boolean representing the existence of the named secret'
runs:
  using: 'node12'
  main: 'dist/index.js'
